services:
    pms:
        image: plexinc/pms-docker:latest
        container_name: pms
        restart: unless-stopped
        network_mode: host 
        volumes:
            - ./pms:/config
            - ./pms:/transcode
        environment:
            TZ: America/New_York
    tvserver:
        image: eswardudi/python-ffmpeg:latest
        container_name: tvserver
        restart: unless-stopped
        network_mode: host
        volumes:
            - .:/app
        working_dir: /app
        command: /bin/bash tvserver.sh config.txt
        environment:
            DEVICE_ID: TVSERVER:4
            SERVER_IP: 127.0.0.1
            SERVER_PORT: 5004